### ISSUE TITLE
压缩率问题

### ISSUE THREAD

**Issue by heivens** [I2-Multimedia-Lab/PoLoPCAC#2]
作者您好，我尝试使用data/ScanNet下给出的示例数据进行压缩，获得了data/ScanNet_compressed下的一系列文件，如图所示：
![image](https://github.com/I2-Multimedia-Lab/PoLoPCAC/assets/52856640/728aa6e5-18b3-4721-996d-8ae1b4489480)
但我发现data/ScanNet下的原始数据大小是3.39MB，而data/ScanNet_compressed下的文件总大小为3.05MB，这压缩率似乎过低，并且似乎跟bpp的结果不太符合，请问这是正常的吗

**Comment by youkangGG** [comment]
您好，谢谢您对我们工作的关注。

本模型关注的是点云的属性压缩。以`ScanNet/scene0011_00_vh_clean_2.ply`为例，其第1组的颜色属性被保存至`.c.bin`, 后续分组的颜色属性被依次压缩后保存至`.0.bin`~`.15.bin`。`.geo.bin`文件保存了原始点云的几何坐标信息，仅辅助解码端用于属性的解码。

如果您仅计算`size(.0.bin)+size(.1.bin)+...+size(.15.bin)+size(.c.bin)`的文件大小，可以看到一共为343KB（即11.84 bpp），与论文中及代码中所报告的结果相符。

`ScanNet/scene0011_00_vh_clean_2.ply`点云包含237360个点，每个点又包含3个32位浮点数坐标(x, y, z)和3个8位整型颜色属性(r, g, b)，因此其数据大小为`237360*(32*3)[geometry]+237360*(8*3)[attribute]=28483200(bit)=3.39(MB)`；
使用PoLoPCAC对其属性数据压缩后，其数据大小为`237360*(32*3)[geometry]+343(KB)[attribute]=3.05(MB)`;

因此，您的结果是正常的。我们的bpp仅报告了属性压缩的部分。如果需要对点云整体的更低的码率，请考虑结合几何压缩的模型。

**Comment by heivens** [comment]
明白了，感谢您的回复



---原始邮件---
发件人: "Kang ***@***.***&gt;
发送时间: 2024年6月26日(周三) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [I2-Multimedia-Lab/PoLoPCAC] 压缩率问题 (Issue #2)




 
您好，谢谢您对我们工作的关注。
 
本模型关注的是点云的属性压缩。以ScanNet/scene0011_00_vh_clean_2.ply为例，其第1组的颜色属性被保存至.c.bin, 后续分组的颜色属性被依次压缩后保存至.0.bin~.15.bin。.geo.bin文件保存了原始点云的几何坐标信息，仅辅助解码端用于属性的解码。
 
如果您仅计算size(.0.bin)+size(.1.bin)+...+size(.15.bin)+size(.c.bin)的文件大小，可以看到一共为343KB（即11.84 bpp），与论文中及代码中所报告的结果相符。
 
ScanNet/scene0011_00_vh_clean_2.ply点云包含237360个点，每个点又包含3个32位浮点数坐标(x, y, z)和3个8位整型颜色属性(r, g, b)，因此其数据大小为237360*(32*3)[geometry]+237360*(8*3)[attribute]=28483200(bit)=3.39(MB)；
 使用PoLoPCAC对其属性数据压缩后，其数据大小为237360*(32*3)[geometry]+343(KB)[attribute]=3.05(MB);
 
因此，您的结果是正常的。我们的bpp仅报告了属性压缩的部分。如果需要对点云整体的更低的码率，请考虑结合几何压缩的模型。
